language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"

branches:
  only:
    - master
before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install
script:
  - npm run build
after_success:
  - cd .vuepress/dist
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add -A
  - git commit -m "depoly at `date +"%Y-%m-%d %H:%M"`"
  - git push --quiet --force "https://${GH_TOKEN}@github.com/ssssssss-team/spider-flow-site.git" master:gh-pages